### ISSUE TITLE
Display pairs vertically

### ISSUE THREAD

**Issue by Foul** [MarcinOrlowski/crypto-tracker-plasmoid#11]
For the moment, the different pairs are displayed in horizontal mode, possible to choose between horizontal and vertical?

**Comment by MarcinOrlowski** [comment]
Not sure I got what you mean. Mind creating mockup of the layout?

**Comment by Foul** [comment]
here is a picture : https://img.super-h.fr/images/f54d13721d7dca03b7f2e72760e363f4.png

**Comment by MarcinOrlowski** [comment]
Please attach image to the ticket. Remote images has tendency to expire.

Anyway, it looks like you want to have horizontal panel but widget should layout vertically?

**Comment by Foul** [comment]
when i want to resize, i can only horizontally.

**Comment by MarcinOrlowski** [comment]
Ok. I will check various variants tomorrow and update the ticket with my findings

**Comment by Foul** [comment]
ok thx :)

**Comment by MarcinOrlowski** [comment]
But there's one thing that you should be aware of :) Widget checks panel orientation. It can be either vertical or horizontal. Stretching panel makes no difference. If it's vertical and you strech it horizontally, it is still **vertical** panel. In vertical panels pairs a re shown... well... vertically :) in horizontal, horizontally. So event there's technically the space for more pair it will not be used because widget is still vertical and technically it uses grid layout with X*Y cells or Y*X depending on orientation.

**Comment by MarcinOrlowski** [comment]
Good news :) This feature is part of next release.
